apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: rnkoaa/mango:latest
        name: web
        imagePullPolicy: IfNotPresent
        env:
        - name: GCLOUD_ENV
          value: "Google Cloud Env."
        - name: CLOUD_ENV
          value: "Google Cloud Env."
        ports:
        - name: http-server
          containerPort: 3000
