version: '3.3'

services:
  keycloak:
    container_name: keycloak
    image: rnkoaa/keycloak:3.3.0
    environment:
      DB_VENDOR: POSTGRES
      KEYCLOAK_LOGLEVEL: DEBUG
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

      # Workaround for container using legacy Docker links, resulting in
      # "WFLYCTL0211: Cannot resolve expression 'jdbc:postgresql://${env.POSTGRES_PORT_5432_TCP_ADDR}...")n
      POSTGRES_DB_HOST: postgres

      # Default keycloak admin credentials.
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8090:8080"
    networks:
      - scloudstore_catalogs_backend_db
    volumes:
      - keycloak_providers:/opt/jboss/keycloak/providers
      - keycloak_themes:/opt/jboss/keycloak/themes

networks:
  scloudstore_catalogs_backend_db:
    external: true

volumes:
  keycloak_providers:
    external: true
  keycloak_themes:
    external: true
