version: '2'

services:
  master:
    image: rnkoaa/jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Dhudson.footerURL=http://rfstaging.asuscomm.com"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/jenkins_home
