version: '2'

services:
  jenkins-data:
    build: ./jenkins-data
    container_name: jenkins-data

  master:
    image: rnkoaa/jenkins
    environment:
      JAVA_OPTS: "-Xmx2048m -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Dhudson.footerURL=http://rfstaging.asuscomm.com"
    container_name: jenkins
    privileged: true
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes_from:
      - jenkins-data
    networks:
      - infrastructure

networks:
  infrastructure:
    driver: bridge
# For access to host docker daemon
#      - /usr/local/bin/docker:/bin/docker
#      - /var/run/docker.sock:/var/run/docker.sock
