version: '2'

services:
  jenkins-data:
    build: ./jenkins-data
    container_name: jenkins-data

  master:
    image: rnkoaa/jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Dhudson.footerURL=http://rfstaging.asuscomm.com"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes_from:
      - jenkins-data
# For access to host docker daemon
#      - /usr/local/bin/docker:/bin/docker
#      - /var/run/docker.sock:/var/run/docker.sock
