version: '2'

services:
  master:
    image: rnkoaa/jenkins:lts
    environment:
      JAVA_OPTS: "-Xmx2048m -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Dhudson.footerURL=http://rfstaging.asuscomm.com"
    container_name: jenkins
    privileged: true
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/local/bin/docker:/bin/docker
    networks:
      - infrastructure_net
      - jenkins_net

networks:
  jenkins_net:
    driver: bridge
  infrastructure_net:
    external: true

volumes:
  jenkins_home:
