version: '2'

services:
  nexus-3:
    image: "rnkoaa/nexus3:latest"
    build: .
    environment:
#      JAVA_OPTS: "-Djava.awt.headless=true"
      JAVA_MIN_MEM: "256M"
      JAVA_MAX_MEM: "512M"
      JKS_PASSWORD: "$JKS_PASSWORD"
    ports:
      - "5000:5000"
      - "8081:8081"
    volumes:
      - /var/jenkins_home
