version: '2'

services:
  nexus-master:
    image: rnkoaa/nexus3:latest
    environment:
      JAVA_MIN_MEM: "256M"
      JAVA_MAX_MEM: "512M"
#      JKS_PASSWORD: "$JKS_PASSWORD"
    container_name: nexus
    privileged: true
    ports:
      - "5000:5000"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - nexus3-data:/nexus-data

volumes:
  nexus3-data: